### PR TITLE
Add feature for Run Cocos2d JS projects in browser, issue #12

### PR DESCRIPTION
**Pull request by ayuer**
Using CocoaHttpServer c6156087db381a6d233703f9686b8676af6d72a4, let me know if this is the right way to use 3rd party code.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
a few comments:
In the not so-long-term-future, the goal is to have CocosBuilder running on multiplatforms.
The webserver source code should be something cross-platform, IMHO

**Comment by vlidholt** [comment]
I think this solution looks good for the short term, and we could switch to the command line tool later on when it's done. A few thoughts on the implementation:
- I am working on moving stuff away from the app delegate, as it is already way to large. So for new features, such as this, it would be better if we could move the logic to it's own class and only do as few calls to it as possible from the app delegate.
- Have you tested it with all cases? Opening project, closing projects, updating the publish directory?
- The logging using DDLog, is there a reason for using a new logger? In this case, why only by the server? I say use NSLog, or we make an overall strategy for logging errors throughout CocosBuilder (this may need some research to be done right and what would the benefits be?).
- Would it be possible to acquire a unique port number (in case 54321 is being used by some other program)?

**Comment by ayuer** [comment]
Agree on the long term cross-platform solution, I actually thought about using the python web server as in the HTML5 tests did, but it seems much more work needed.

@vlidholt to comment on your comments:
1, Sure, let me do that
2, I tested opening and closing, will test more on updating publish directory
3, I was concerned about the DDLog too, I can switch back to use NSLog, it's just come with the demo code for the CocoaHTTPServer
4, We can do that, if 54321 is taken and we will leave it to the kernel to pick a port for us, CocoaHTTPServer supports this feature already.

**Comment by ricardoquesada** [comment]
We should stop implementing things twice. If we need an HTTP server for CCB we need to do it right from scratch. 
IMHO this is a waste of resources.

**Comment by vlidholt** [comment]
Agreed that we shouldn't implement things twice. In this particular case, most of the code are hooks in CocosBuilder for when to start, stop and restart the web-server, there is only little code that could be reused whichever solution we choose to go with. As the web-server is already implemented, I say that we go with this for now if it is a stable solution.

**Comment by vlidholt** [comment]
This pull request couldn't be merged automatically, in the future please resolve the conflicts before sending the pull request. When I started resolving the conflicts I noted a couple of issues with how you have updated the project file. The settings for the whole project has been changed to ARC, which is not a good idea since the only files that are actually using ARC is the http-server. Instead for these particular files the -fobjc-arc should be added for these files only (not the other way around).

Also, check that:
- The browser is opened after the publish have been completed (if possible also reload/clear the cache of browser)
- The server is started correctly when a new project is created
- It is possible to select different browsers (Safari, Chrome, Firefox), this could be a sub menu to the 'Run in Browser' command. Ideally, if a specific browser isn't installed gray out the option.

**Comment by ayuer** [comment]
Changed the -fobj-arc to only do that for the few files that is needed, I was rely on xcode to do the work before, don't know they done it that way.

Add support for multiple browser, don't know how to determine if one browser is existing on a machine yet, any idea?

For reload/clear cache, there may be some param to each browser, I need to dig into that, maybe add later.

**Pull request merged**
