### PR TITLE
[develop] memory leaks, etc.

### PR DESCRIPTION
**Pull request by donaldalanmorrison**
Memory leaks and small bugs identified by static analyzer.  Tack!

### CODE REVIEW

**Comment by vlidholt** [comment]
I see many of the memory leaks are plugged by just adding an autorelease. I think at least some of them are objects that need to stay a longer time in memory and should be released in the dealloc method.

Have you tested all the changes that you have made? (E.g. running CocosBuilder with NSZombie turned on and making sure all the changed code is covered)

**Comment by donaldalanmorrison** [comment]
I only tested with the Static Analyzer.

**Comment by donaldalanmorrison** [comment]
Vik: I've run with NSZombies enabled and opened the sample projects & run Animation - Play.  The substring "zombie" isn't in the console output.

Note: "Build for Profiling" is currently broken.  Enabling NSZombies was performed by holding the alt key and selecting Product - Run (and checking the zombie box).

**Comment by donaldalanmorrison** [comment]
If Fragaria is removed from the build, Build for Profiling still fails in CocosScene.m, because the compiler can't see that CGPoint and NSPoint are equivalent on the current target platform.

Prior to OSX 10.5 they weren't equivalent on 64-bit builds:

https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_DataTypes/Reference/reference.html#//apple_ref/doc/uid/20000018-SW20

Keep support for 10.4 and below?

**Comment by donaldalanmorrison** [comment]
@vlidholt: If the static analyzer doesn't convince you, an alternative resolution would be to convert CocosBuilder to ARC (Automatic Reference Counting), and for external libs use -fno-objc-arc.  The downside is GCC doesn't support ARC, only the Apple LLVM Compiler (clang).

"If you build it, they will come." -- Field of [NSZombie] Dreams

**Comment by vlidholt** [comment]
I've now plugged the memory leaks! (Most external libs aren't touched though, so I may have a look at them later)

**Comment by donaldalanmorrison** [comment]
<(^.^)> <(^.^<) (>^.^)> <(^.^)> <(^.^<) (>^.^)>

o/\o ^5 >_>^ ^<_<

**Pull request closed without merging**
