### PR TITLE
Fix spritesheet rotation bug

### PR DESCRIPTION
**Pull request by sabshire**

### CODE REVIEW

**Comment by vlidholt** [comment]
Thanks for the bug fix! Please let me know if you want your name & website in the authors file. :)

**Comment by vlidholt** [comment]
Oh, and in the future, it would make merging easier if you could send pull requests to the develop branch. Thanks again!

**Comment by sabshire** [comment]
Sure, you can include it if you want.  I'll do that on the develop branch next time.  Just learning how to use git, and really didn't intend for it to go to the master branch.

**Comment by vlidholt** [comment]
What name/website do you want in there?

**Comment by sabshire** [comment]
Stacey Abshire http://www.4haks.net

**Pull request merged**
