### PR TITLE
New Feature - Show/Hide functionality for Resources & Inspector Panels

### PR DESCRIPTION
**Pull request by atzoum**
Application usability enhancement.

Added two buttons in the main toolbar for "XCode-like" left/right panel show hide functionality.

User now can customize the application's window view by selecting which panels he wants to see!

### CODE REVIEW

**Comment by atzoum** [comment]
Just added another button for the bottom panel (Timeline Panel).
Also fixed the following BUG: On window resize, if new winHeight is small and Timeline panel is already small, layout breaks.

**Comment by atzoum** [comment]
I believe it is complete now (and bug free!).

**Comment by vlidholt** [comment]
Hi, very nice additions! Please let me know your name and website so that I can include it in the Authors file

**Comment by atzoum** [comment]
Thanks Viktor, my name is Aris Tzoumas. No website :)

**Pull request merged**
